server:
  port: 8390

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

management:
  server:
    port: 8400
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}

sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SENTRY_ENV}
  release: 0.0.1
  servername: aws-eks-container
  send-default-pii: true
  attach-stacktrace: true
  sample-rate: ${SENTRY_SAMPLE_RATE}
