server:
  port: 8390

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

management:
  server:
    port: 8400
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

spring:
  security:
    oauth2:
      client:
        provider:
          maat-api:
            token-uri: ${MAAT_API_OAUTH_URL}
        registration:
          maat-api:
            client-id: ${MAAT_API_OAUTH_CLIENT_ID}
            client-secret: ${MAAT_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
      resource-server:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}

retry-config:
  max-retries: 3
  min-back-off-period: 5
  jitter-value: 0.75

services:
  maat-api:
    base-url: ${MAAT_API_BASE_URL}
    user-domain: ${services.maat-api.base-url}/api/internal/v1/users
    user-endpoints:
      user-summary-url: ${services.maat-api.user-domain}/summary/{username}

sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SENTRY_ENV}
  release: 0.0.1
  servername: aws-eks-container
  send-default-pii: true
  attach-stacktrace: true
  sample-rate: ${SENTRY_SAMPLE_RATE}
